language: java
jdk:
  - oraclejdk8
install: mvn dependency:resolve
cache:
  directories:
  - $HOME/.m2
  - bundler
  - packages
script:
  - mvn clean install -DskipTests -U -Dmaven.javadoc.skip=true
after_success:
- mvn clean test jacoco:report coveralls:report -DrepoToken=$COVERALLS_REPO_TOKEN -U
